version: 1
send_anonymous_usage_stats: false
project_id: 2e2d28c2-b095-47e1-9804-ac713c722466
default_environment: dev
plugins:
  extractors:
  - name: tap-bitso
    namespace: bitso
    pip_url: -e .
    capabilities:
    - state
    - catalog
    - discover
    - about
    - stream-maps
    settings:
    - name: key
      kind: password
      label: Bitso API Key
      description: Bitso API Key
      sensitive: true
      documentation: https://bitso.com/api_info?python#generating-api-keys
    - name: secret
      kind: password
      label: Bitso API Secret
      sensitive: true
    - name: base_url
      kind: string
      value: https://api.bitso.com
      label: Bitso API base URL
    - name: books
      kind: array
    config:
      books:
      - btc_mxn
      - eth_mxn
    select_filter:
    - '!trades'
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
  - name: target-sqlite
    variant: meltano
    config:
      database: output/${MELTANO_EXTRACT__LOAD_SCHEMA}.db
      batch_size: 500

environments:
- name: dev
venv:
  backend: uv
